### PR TITLE
Update setuptools and zc.buildout versions

### PR DESCRIPTION
**Pull request by tmassman**
Use newest versions for requirements.txt files and unpin versions in buildout configurations.

### CODE REVIEW

**Comment by gforcada** [comment]
@tmassman what's the idea of unpining on the cfg files? They should rather keep the version numbers in sync with requirements.txt IMHO.

**Comment by tmassman** [comment]
@gforcada, well first to make it consistent. In some files they have been pinned, in some not. @MrTango started this [in his last pull request](https://github.com/plone/bobtemplates.plone/pull/241/files) already.
Second, it is way better to use the versions installed with pip into the virtualenv and refer to that from within buildout.

**Comment by gforcada** [comment]
@tmassman so you mean that given we use a virtualenv, not pinning them rather than trying to get the lastest version they will use the one provided by virtualenv?

Stil, IMHO, we should pin them, because every now and then, one forgets to enable a virtualenv, or doesn't know about it (this is bobtemplates.plone, meant to help newcomers as well as seasoned, but newcomers are the ones that will look more for this kind of package generator).

And finally I always add ``allow-picked-versions = false`` to my buildouts, better to fail early and report that there are unpinned versions rather than 2 months later start getting errors because an unpinned dependency got bumped and now all goes astray.

**Comment by MrTango** [comment]
I thing the way how you install it nowerdays, is first ``pip install -r requirements.txt`` and this way you have the correct versions anyway. There is no bootstrap.py anymore, which can give you the wrong versions.
@gforcada I guess the allow-picked-versions = false conflicts with the unset version, so we have to set it in this case. I personally don't use this. Buildout is much better now in showing what is wrong with versions and requirements ;).
For the bobtemplate, maybe we can put the versions for these into a separate place and write them into the templates, so that we don't have to change them in two places all the time.

**Comment by MrTango** [comment]
I merged this, to have the newer version in.
The pinning we can add later with the parameter way.

**Pull request merged**
