### PR TITLE
Pin flake8 to latest (3.3.0) to allow use of latest pycodestyle (2.3.1).

### LINKED ISSUE #194: flake8 version pin (3.0.4) causes version conflict for pycodestyle
Currently, `flake8` is pinned to 3.0.4.  This version of `flake8` restricts the allowable version of `pycodestyle` to `<2.1.0,>=2.0.0`.  But since `pycodestyle` is not pinned, we get the latest (currently 2.3.1), and then a version conflict:

```
Version and requirements information containing pycodestyle:
  Requirement of flake8-todo: pycodestyle<3.0.0,>=2.0.0
  Requirement of flake8>=2.4.0: pycodestyle<2.1.0,>=2.0.0
While:
  Installing.
  Getting section code-analysis.
  Initializing section code-analysis.
  Installing recipe plone.recipe.codeanalysis[recommended].
Error: There is a version conflict.
We already have: pycodestyle 2.3.1
but flake8 3.0.4 requires 'pycodestyle<2.1.0,>=2.0.0'.
```

I have tried to change the `flake8` pin to the latest (`flake8 = 3.3.0`), and this allows buildout to complete.  Alternatively, we could pin `pycodestyle` to a version allowed by `flake8 3.0.4` (`pycodestyle = 2.0.0`).

Thoughts?

### PR DESCRIPTION
**Pull request by fulv**
Fixes #194

### CODE REVIEW

**Comment by fulv** [comment]
Something's not right:  all the failures look like

```
The command "sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install npm" failed and exited with 100 during .
```

Does anybody know what's going on here?

**Comment by tomgross** [comment]
@fulv Shouldn't we pin pycodestyle too, if it is a hard dependency?

**Comment by fulv** [comment]
@tomgross good point!  I added the pin.

**Comment by fulv** [comment]
I don't understand these Travis CI build errors, how can we fix them?

**Comment by jensens** [comment]
I have a rough idea what's going on, stay tuned.

**Comment by ale-rt** [comment]
I wanted to to a similar PR today.

Other versions buildout suggests me to pin are:
```
PyYAML = 3.12
argh = 0.26.2
args = 0.1.0
check-manifest = 0.35
clint = 0.5.1
colorama = 0.3.7
configparser = 3.5.0
createcoverage = 1.5
enum34 = 1.1.6
flake8 = 3.3.0
flake8-blind-except = 0.1.1
flake8-coding = 1.3.0
flake8-debugger = 1.4.0
flake8-deprecated = 1.1
flake8-isort = 2.1.3
flake8-pep3101 = 1.0
flake8-plone-api = 1.2
flake8-plone-hasattr = 0.1
flake8-polyfill = 1.0.1
flake8-print = 2.0.2
flake8-quotes = 0.9.0
flake8-string-format = 0.2.3
flake8-todo = 0.7
isort = 4.2.5
mccabe = 0.6.1
pathtools = 0.1.2
pkginfo = 1.4.1
plone.recipe.codeanalysis = 2.2
plone.testing = 5.0.0
pycodestyle = 2.3.1
pyflakes = 1.5.0
requests-toolbelt = 0.7.1
testfixtures = 4.13.4
twine = 1.8.1
watchdog = 0.8.3
z3c.jbot = 0.7.2
zest.releaser = 6.9
```

**Comment by jensens** [comment]
@alert, shouldn't this be part of plone versions? IIRC most of them are pinned in buildout.coredev (versions.cfg or tests.cfg).

**Comment by ale-rt** [comment]
@jensens, I did not look carefully at the diff.
I meant that the pins should be modified here:

- https://github.com/plone/bobtemplates.plone/blob/master/bobtemplates/plone_addon/buildout.cfg.bob

In fact if you create a package with the currently released version of bobtemplates.plone you can find yourself with a broken precommit hook.

I will open a PR for that.

**Pull request merged**
