### PR TITLE
hide uninstall profile

### LINKED ISSUE #79: hide uninstall profile from quickinstaller
see https://github.com/plone/Products.CMFPlone/issues/811

### PR DESCRIPTION
**Pull request by pbauer**
fixes #79

### CODE REVIEW

**Comment by pbauer** [comment]
I chose to put the relevant code in ``setuphandlers.py``. Not ideal but the alternatives were a) a new file and b) ``interfaces.py``. @tisto ok?

**Comment by tisto** [comment]
@pbauer what would be the default file for this?

**Comment by pbauer** [comment]
@tisto There is no default. Grep your projects and you will find ``setuphandler.py``, ``__init.py__`` and some others. I think my choice is ok since there is no python-file that has more connection with the profile than setuphandler.py.

**Comment by pbauer** [comment]
@tisto what is `Coding magic comment not found`sopposed to be that codeanalysis complains about?

**Comment by tisto** [comment]
@pbauer this is about the required "utf-8" coding header in the first line of the file. No idea why it fails for your pull request and not for master.

**Pull request merged**
