### PR TITLE
fix #84 Make travis cache the egg directory of the generated package.

### LINKED ISSUE #84: Make travis cache the egg directory of the generated package.
This could significantly speed up the travis build time. 8 minutes per build is too much.

### PR DESCRIPTION
**Pull request by jensens**
see #84

### CODE REVIEW

**Comment by tisto** [comment]
@jensens not exactly what I meant but nice anyways. :)

I was thinking about a way to speed up the travis job for bobtemplates.plone itself. We currently cache the eggs of the main buildout but the tests create a new package buildout that takes time to run and that does not use any egg caching so far.

**Comment by jensens** [comment]
ops :)

**Comment by jensens** [comment]
but wait, since both are running on the same travis and both are using the absolute path in travis.cfg this will fix it too, right?

**Comment by jensens** [comment]
it does not fix it, because it runs buildout.cfg - not travis.cfg - in the tests

**Comment by jensens** [comment]
sorry, i'am trying to find the place where (in code) do the tests create a new package buildout?

**Comment by jensens** [comment]
@tisto @ pbauer this one is ready for merge, review appreciated, build/test time on travis reduced from 8 to 9 min per variant down to ~1:30 with warmed up cache.

**Comment by tisto** [comment]
@jensens that's great! The reason why I haven't merged the pr yet is that I'm a bit concerned about the complexity of our overall build process. I'm wondering if would be possible to use a ".buildout" egg cache in the travis home root instead of injecting the cache into the buildout configuration.

**Comment by jensens** [comment]
hmm, do you mean to add a global ``$home/.buildout/default.cfg`` like this?

    [buildout]
    download-cache = /home/travis/buildout-cache/downloads
    eggs-directory = /home/travis/buildout-cache/eggs

I think this could work and is much simpler. I give it a try.

**Comment by tisto** [comment]
@jensens yes. this is what I had in mind.

**Comment by jensens** [comment]
indeed, much simpler this way. I just did not thought about the possibility of global configuration.

**Comment by jensens** [comment]
@tisto ok, all green, I squashed it to one commit - if tests are still green (no reason why not) its imo really ready for merge - and imo this way a very elegant solution.

**Comment by tisto** [comment]
AWESOME! Feel free to merge when the build is green.

**Comment by mauritsvanrees** [comment]
The Travis jobs for bobtemplates.plone are fast, so this apparently works, but I wonder how. I see one problem:

- We now have a `$HOME/.buildout/default.cfg` that says `eggs-directory = $HOME/buildout-cache/eggs`
- The travis.cfg of the generated package ultimately extends https://raw.githubusercontent.com/collective/buildout.plonetest/master/buildout-cache.cfg which says `eggs-directory = ${buildout:directory}/buildout-cache/eggs`

So it looks to me like the generated package listens to `buildout-cache.cfg` and will start creating eggs in `/home/travis/build/plone/bobtemplates.plone/test.plone_addon/buildout-cache/eggs`
It is faster than it is supposed to. Am I missing something?

**Comment by mauritsvanrees** [comment]
Note: the label cleanup I just did on this issue has nothing to do with my comment, but pr review has been done and pr ready seems unneeded since this was merged already. Just brushing some corners. :-)

**Pull request merged**
