### PR TITLE
add isort configuration

### PR DESCRIPTION
**Pull request by jensens**
Currently isort style checks are enabled, but no config was set. Added config according to http://docs.plone.org/develop/styleguide/python.html#grouping-and-sorting

### CODE REVIEW

**Comment by tisto** [comment]
@gforcada I somehow lost track of the isort discussion. Would you mind having a quick look at this pr?

@jensens pr needs rebase after I merged your first pr.

**Comment by jensens** [comment]
thanks, rebased

**Comment by do3cc** [comment]
@jensens can you add a link to the docs in this file?
The configuration is quite confusing and one might change the line_length to 80, not understanding it's meaning

**Comment by jensens** [comment]
@do3cc good point, I'll do.

**Comment by gforcada** [comment]
Thanks!

**Pull request merged**
