### PR TITLE
Better docs

### PR DESCRIPTION
**Pull request by do3cc**
@svx Is this cool?

### CODE REVIEW

**Comment by svx** [comment]
yes :+1:  !!!

**Comment by do3cc** [comment]
Extending tests.py to run at least longtest

**Comment by jensens** [comment]
What is the state here?

**Comment by svx** [comment]
@do3cc do you  know the status ?

**Comment by tisto** [comment]
We can not merge as long as travis is failing.

**Comment by tisto** [comment]
@do3cc fyi: I manually merged this pull request, except the longtest check since that fails on travis. It would be nice if we could make that work as well...

**Comment by do3cc** [comment]
I'd love to, but wont really find the time in the next three months :-(

**Pull request closed without merging**
