### PR TITLE
make sure to use the newest python version 

### PR DESCRIPTION
**Pull request by pbauer**
the one in virtualenv is too old for Plone 5.1

### CODE REVIEW

**Comment by jensens** [comment]
hmm, strange, just declaring
```
python:
  - 2.7.14
```
does not help?

**Comment by pbauer** [comment]
No. The command `virtualenv` uses a different python by default.

**Comment by jensens** [comment]
thats odd

**Comment by MrTango** [comment]
I solved this in EasyNewsletter by  doing "pip install --upgrade virtualenv" in before_install section

**Pull request merged**
