### PR TITLE
Workon support for Python 3.10

### PR DESCRIPTION
**Pull request by pbauer**
This depends on https://github.com/domenkozar/mr.bob/pull/92

### CODE REVIEW

**Comment by mamico** [comment]
@pbauer I've synced the branch with the main branch, and attempted to fix your issue, updating the `tox.ini` inside the template.

btw, I don't have any clue about slowness during GHA tests, locally are faster. 

p.s. I'm sorry, if I directly merged in your branch :)

**Comment by MrTango** [comment]
the test take always a while, we are testing a lot, but might be that GH is not outperforming it self here.
But hey it's free ;)

**Review by MrTango — APPROVED** [review]
LGTM, good to merge after build is done and green

**Comment by MrTango** [comment]
I also dropped Python 3.7 in the CI, that should save some time.

**Pull request merged**
