### PR TITLE
Fix coveralls by converting .coverage from pickle to json

### PR DESCRIPTION
**Pull request by pbauer**
Not sure if this is the current best practice. See https://community.plone.org/t/createcoverage-coveralls-io-version-conflicts/1188

### CODE REVIEW

**Comment by pbauer** [comment]
At least this works for https://github.com/collective/collective.fieldedit. See https://coveralls.io/github/collective/collective.fieldedit

**Comment by hvelarde** [comment]
sorry for the delay; I don't see the point on merging this: what was the problem you are trying to solve?

**Comment by jensens** [comment]
The point is, the pickle format created by the version of coverage used by Plone by default do not store json but pickles, but coveralls expect json. 
Sorry, after all it works for me and others I now merged it to at least have some solution. Proposals for better solutions or new PRs welcome.

**Comment by hvelarde** [comment]
I don't understand: I have this installed and working in literally dozens of add-ons based on Plone default configuration which uses `coverage = 4.2` as stated above; see for instance `collective.cover` as mentioned before by @mauritsvanrees:

* https://github.com/collective/collective.cover/blob/master/.travis.yml#L38-L41
* https://coveralls.io/github/collective/collective.cover

**Pull request merged**
