### PR TITLE
full tests with appveyor

### PR DESCRIPTION
**Pull request by loechel**

### CODE REVIEW

**Comment by jensens** [comment]
I disabled the Appveyor webhook for now. If you plan to go on with this just enable it again.

**Comment by MrTango** [comment]
I really would like to have some windows support in the CI, but these changes are outdated now and I'm woundering if we can't solve this with Github Actions by now? Since we are using GH Action already anyway for the linux tests.

**Comment by MrTango** [comment]
Be ware that the Test matrix has changed a lot.

**Comment by jensens** [comment]
Yes, this should work with GH actions too these days (and back in 2018 this was not invented). I added build tests for buildout.coredev on Windows as well as a reference.

**Comment by jensens** [comment]
There was no activity on this for a while. I close this request for now. If you plan to work further on this please reopen and go on.

**Pull request closed without merging**
