### PR TITLE
Simplify concatenation of .rst files for setup.py.

### PR DESCRIPTION
**Pull request by thet**

### CODE REVIEW

**Comment by jensens** [comment]
:+1:

**Comment by tisto** [comment]
+1 BTW: Why do we have CONTRIBUTORS.rst separated in the first place? This does not make much sense IMHO. This can be just a section in the README.rst.

**Comment by tisto** [comment]
This pr needs a rebase btw.

**Comment by svx** [comment]
@tisto please do **not** do that, please keep a separate  CONTRIBUTORS.rst.
It would be awesome if bobtemplates would follow http://docs.plone.org/about/documentation_styleguide.html.

We are working hard on setting up ci tests for the docs and all parts which are included into the docs, like bobtemplates.
For doing so, it is much better and easier to follow the best practices, that is why we have them :)

**Comment by frisi** [comment]
@svx the change is ok. in fact @tisto only added the headlines to the files instead of magically adding them just to the longdesc in setup.py.
bobtemplates.plone is following the best practices for readme/changes/contributors

**Comment by svx** [comment]
@frisi thanks ! But :),  I am not saying that the PR is wrong, I am just answering to @tisto 's question about why it is a separate file :)

**Comment by frisi** [comment]
sorry @svx, i did not read the whole thread but only looked at the files changed :-(

**Comment by thet** [comment]
rebased

**Comment by tisto** [comment]
This pr removed one of the "\n". We have to check if this breaks the ReST when doing releases...

**Comment by jensens** [comment]
hmm, from what i see its enough /n in there. but to be paranoid we could enhance to a ``'\n\n'.join(....``
@thet may you do this?

**Comment by thet** [comment]
OOTB, it produces the following output:
```
.. This README is meant for consumption by humans and pypi. Pypi can render rst files so please do not use Sphinx features.
   If you want to learn more about writing documentation, please check out: http://docs.plone.org/about/documentation_styleguide_addons.html
   This text does not appear on pypi or github. It is a comment.

==============================================================================
lineage.controlpanels
==============================================================================

Tell me what your product does

Features
--------

- Can be bullet points

Not available in Lineage Childsites
-----------------------------------

- migrate-to-emaillogin
- resourceregistry-controlpanel

- usergroup-controlpanel
- usergroup-userprefs
- usergroup-groupprefs
- usergroup-groupmembership
- usergroup-usermembership
- usergroup-groupdetails

- prefs_install_products_form
- upgrade_products
- install_products
- uninstall_products



Examples
--------

This add-on can be seen in action at the following sites:
- Is there a page on the internet where everybody can see the features?


Documentation
-------------

Full documentation for end users can be found in the "docs" folder, and is also available online at http://docs.plone.org/foo/bar


Translations
------------

This product has been translated into

- Klingon (thanks, K'Plai)


Installation
------------

Install lineage.controlpanels by adding it to your buildout::

    [buildout]

    ...

    eggs =
        lineage.controlpanels


and then running ``bin/buildout``


Contribute
----------

- Issue Tracker: https://github.com/collective/lineage.controlpanels/issues
- Source Code: https://github.com/collective/lineage.controlpanels
- Documentation: https://docs.plone.org/foo/bar


Support
-------

If you are having issues, please let us know.
We have a mailing list located at: project@example.com


License
-------

The project is licensed under the GPLv2.

Contributors
============

- Johannes Raggam, thetetet@gmail.com

Changelog
=========


1.0a1 (unreleased)
------------------

- Initial release.
  [thet]
```

**Comment by thet** [comment]
^^ that should be OK, even though there are no extra newlines in each individual file.
But I prefer two newlines between sections, so I'll add an extra ``\n``.

**Comment by thet** [comment]
Now:
```
.. This README is meant for consumption by humans and pypi. Pypi can render rst files so please do not use Sphinx features.
   If you want to learn more about writing documentation, please check out: http://docs.plone.org/about/documentation_styleguide_addons.html
   This text does not appear on pypi or github. It is a comment.

==============================================================================
lineage.controlpanels
==============================================================================

Tell me what your product does

Features
--------

- Can be bullet points

Not available in Lineage Childsites
-----------------------------------

- migrate-to-emaillogin
- resourceregistry-controlpanel

- usergroup-controlpanel
- usergroup-userprefs
- usergroup-groupprefs
- usergroup-groupmembership
- usergroup-usermembership
- usergroup-groupdetails

- prefs_install_products_form
- upgrade_products
- install_products
- uninstall_products



Examples
--------

This add-on can be seen in action at the following sites:
- Is there a page on the internet where everybody can see the features?


Documentation
-------------

Full documentation for end users can be found in the "docs" folder, and is also available online at http://docs.plone.org/foo/bar


Translations
------------

This product has been translated into

- Klingon (thanks, K'Plai)


Installation
------------

Install lineage.controlpanels by adding it to your buildout::

    [buildout]

    ...

    eggs =
        lineage.controlpanels


and then running ``bin/buildout``


Contribute
----------

- Issue Tracker: https://github.com/collective/lineage.controlpanels/issues
- Source Code: https://github.com/collective/lineage.controlpanels
- Documentation: https://docs.plone.org/foo/bar


Support
-------

If you are having issues, please let us know.
We have a mailing list located at: project@example.com


License
-------

The project is licensed under the GPLv2.


Contributors
============

- Johannes Raggam, thetetet@gmail.com


Changelog
=========


1.0a1 (unreleased)
------------------

- Initial release.
  [thet]
```

**Pull request merged**
